/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_api_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations["logout_api_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["me_api_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/conexiones": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List All */
    get: operations["list_all_api_conexiones_get"];
    put?: never;
    /** Create */
    post: operations["create_api_conexiones_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/conexiones/probar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Test */
    post: operations["test_api_conexiones_probar_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/conexiones/{cid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove */
    delete: operations["remove_api_conexiones__cid__delete"];
    options?: never;
    head?: never;
    /** Edit */
    patch: operations["edit_api_conexiones__cid__patch"];
    trace?: never;
  };
  "/api/conexiones/{cid}/boards": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Boards */
    get: operations["boards_api_conexiones__cid__boards_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/conexiones/{cid}/campos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fields */
    get: operations["fields_api_conexiones__cid__campos_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cuentas": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Accounts */
    get: operations["accounts_api_cuentas_get"];
    put?: never;
    /** Add Account */
    post: operations["add_account_api_cuentas_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/proyectos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Projects */
    get: operations["projects_api_proyectos_get"];
    put?: never;
    /** Create */
    post: operations["create_api_proyectos_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/proyectos/{pid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Archive */
    delete: operations["archive_api_proyectos__pid__delete"];
    options?: never;
    head?: never;
    /** Edit */
    patch: operations["edit_api_proyectos__pid__patch"];
    trace?: never;
  };
  "/api/cartera": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Portfolio
     * @description Una card por proyecto visible, ordenadas por riesgo.
     */
    get: operations["portfolio_api_cartera_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/proyectos/{pid}/cumplimiento": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Compliance */
    get: operations["compliance_api_proyectos__pid__cumplimiento_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/proyectos/{pid}/sprints/{sid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Sprint Detail */
    get: operations["sprint_detail_api_proyectos__pid__sprints__sid__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/proyectos/{pid}/recalcular": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh */
    post: operations["refresh_api_proyectos__pid__recalcular_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/proyectos/{pid}/tablero": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Board
     * @description Tablero de Jira del sprint activo (solo lectura).
     */
    get: operations["board_api_proyectos__pid__tablero_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AccountIn */
    AccountIn: {
      /** Name */
      name: string;
    };
    /** AccountOut */
    AccountOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
    };
    /** ActiveOut */
    ActiveOut: {
      /** Name */
      name: string;
      /** Day */
      day: number;
      /** Days */
      days: number;
      /** Planned */
      planned: number;
      /** Burned */
      burned: number;
      /** Pct */
      pct: number | null;
    };
    /** BoardOut */
    BoardOut: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Key */
      key: string;
    };
    /**
     * CardOut
     * @description Una card del panel de cartera.
     */
    CardOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Account */
      account: string;
      /** Light */
      light: string;
      last: components["schemas"]["SprintOut"] | null;
      active: components["schemas"]["ActiveOut"] | null;
      /** Trend */
      trend: (number | null)[];
      month: components["schemas"]["MonthOut"] | null;
      /** Error */
      error?: string | null;
    };
    /** ComplianceOut */
    ComplianceOut: {
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      /** Sprints */
      sprints: components["schemas"]["SprintOut"][];
      /** Months */
      months: components["schemas"]["MonthOut"][];
    };
    /** ConnIn */
    ConnIn: {
      /** Name */
      name: string;
      /**
       * Site
       * Format: uri
       */
      site: string;
      /** Email */
      email: string;
      /** Token */
      token?: string | null;
      /** Sp Field */
      sp_field?: string | null;
      /**
       * Skip Subtasks
       * @default true
       */
      skip_subtasks: boolean;
    };
    /**
     * ConnOut
     * @description Nunca incluye el token: solo sus últimos 4 caracteres.
     */
    ConnOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Kind */
      kind: string;
      /** Site */
      site: string | null;
      /** Email */
      email: string | null;
      /** Token Last4 */
      token_last4: string | null;
      /** Sp Field */
      sp_field: string | null;
      /** Skip Subtasks */
      skip_subtasks: boolean;
      /** Status */
      status: string;
      /** Last Error */
      last_error: string | null;
      /** Checked At */
      checked_at: string | null;
      /**
       * Projects
       * @default 0
       */
      projects: number;
    };
    /** Counts */
    Counts: {
      /** Total */
      total: number;
      /** Todo */
      todo: number;
      /** Doing */
      doing: number;
      /** Blocked */
      blocked: number;
      /** Done */
      done: number;
    };
    /** DetailOut */
    DetailOut: {
      sprint: components["schemas"]["SprintOut"];
      /** Lines */
      lines: components["schemas"]["LineOut"][];
    };
    /** FieldOut */
    FieldOut: {
      /** Id */
      id: string;
      /** Name */
      name: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Health */
    Health: {
      /** Status */
      status: string;
      /** Version */
      version: string;
    };
    /** LineOut */
    LineOut: {
      /** Key */
      key: string;
      /** Title */
      title: string;
      /** Status */
      status: string;
      /** Assignee */
      assignee: string | null;
      /** Sp */
      sp: number | null;
      /** Done */
      done: boolean;
      /** Done At */
      done_at: string | null;
      /** Sprints */
      sprints: string[];
      /** Burned */
      burned: boolean;
      /** Burn Sprint */
      burn_sprint: string | null;
      /** Reason */
      reason: string;
    };
    /** LoginIn */
    LoginIn: {
      /** Email */
      email: string;
      /** Password */
      password: string;
    };
    /** Me */
    Me: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** Name */
      name: string;
      /** Role */
      role: string;
      /** Must Change Pwd */
      must_change_pwd: boolean;
    };
    /** MonthOut */
    MonthOut: {
      /** Month */
      month: string;
      /** Planned */
      planned: number;
      /** Burned */
      burned: number;
      /** Pct */
      pct: number | null;
      /** Light */
      light: string;
      /** Sprints */
      sprints: number;
    };
    /** PersonOut */
    PersonOut: {
      /** Name */
      name: string;
      /** Planned */
      planned: number;
      /** Burned */
      burned: number;
      /** Pct */
      pct: number | null;
    };
    /** ProjectIn */
    ProjectIn: {
      /** Name */
      name: string;
      /**
       * Account Id
       * Format: uuid
       */
      account_id: string;
      /**
       * Conn Id
       * Format: uuid
       */
      conn_id: string;
      /** Board Id */
      board_id: number;
      /** Board Name */
      board_name: string;
      /** From Sprint */
      from_sprint?: string | null;
      /** Managers */
      managers?: string[];
    };
    /** ProjectOut */
    ProjectOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /**
       * Account Id
       * Format: uuid
       */
      account_id: string;
      /** Account */
      account: string;
      /** Conn Id */
      conn_id: string | null;
      /** Board Id */
      board_id: number | null;
      /** Board Name */
      board_name: string | null;
      /** From Sprint */
      from_sprint: string | null;
      /** Managers */
      managers: string[];
    };
    /** SprintBoardOut */
    SprintBoardOut: {
      sprint: components["schemas"]["SprintInfo"] | null;
      counts: components["schemas"]["Counts"];
      /** Done Pct */
      done_pct: number | null;
      /** Cards */
      cards: components["schemas"]["TicketOut"][];
      /** Notice */
      notice?: string | null;
    };
    /** SprintInfo */
    SprintInfo: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** State */
      state: string;
      /**
       * Start
       * Format: date-time
       */
      start: string;
      /**
       * End
       * Format: date-time
       */
      end: string;
      /** Day */
      day: number;
      /** Days */
      days: number;
      /** Time Pct */
      time_pct: number;
    };
    /** SprintOut */
    SprintOut: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /**
       * Start
       * Format: date-time
       */
      start: string;
      /**
       * End
       * Format: date-time
       */
      end: string;
      /** State */
      state: string;
      /** Planned */
      planned: number;
      /** Burned */
      burned: number;
      /** Pct */
      pct: number | null;
      /** Light */
      light: string;
      /** Unestimated */
      unestimated: number;
      /** Provisional */
      provisional: boolean;
      /** People */
      people: components["schemas"]["PersonOut"][];
    };
    /** TestIn */
    TestIn: {
      /**
       * Site
       * Format: uri
       */
      site: string;
      /** Email */
      email: string;
      /** Token */
      token?: string | null;
      /** Conn Id */
      conn_id?: string | null;
    };
    /** TestOut */
    TestOut: {
      /** Ok */
      ok: boolean;
      /** User */
      user?: string | null;
      /** Sp Field */
      sp_field?: string | null;
      /** Error */
      error?: string | null;
    };
    /** TicketOut */
    TicketOut: {
      /** Key */
      key: string;
      /** Title */
      title: string;
      /** Status */
      status: string;
      /** Lane */
      lane: string;
      /** Type */
      type: string;
      /** Priority */
      priority: string;
      /** Assignee */
      assignee: string | null;
      /** Sp */
      sp: number | null;
      /** Labels */
      labels: string[];
      /** Updated */
      updated: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  login_api_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_api_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me_api_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
    };
  };
  list_all_api_conexiones_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConnOut"][];
        };
      };
    };
  };
  create_api_conexiones_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConnIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConnOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  test_api_conexiones_probar_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TestIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TestOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remove_api_conexiones__cid__delete: {
    parameters: {
      query: {
        confirm: string;
      };
      header?: never;
      path: {
        cid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  edit_api_conexiones__cid__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConnIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConnOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  boards_api_conexiones__cid__boards_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BoardOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  fields_api_conexiones__cid__campos_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FieldOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  accounts_api_cuentas_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountOut"][];
        };
      };
    };
  };
  add_account_api_cuentas_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccountIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  projects_api_proyectos_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectOut"][];
        };
      };
    };
  };
  create_api_proyectos_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  archive_api_proyectos__pid__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  edit_api_proyectos__pid__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  portfolio_api_cartera_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CardOut"][];
        };
      };
    };
  };
  compliance_api_proyectos__pid__cumplimiento_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ComplianceOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  sprint_detail_api_proyectos__pid__sprints__sid__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pid: string;
        sid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DetailOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  refresh_api_proyectos__pid__recalcular_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  board_api_proyectos__pid__tablero_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SprintBoardOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
