/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_api_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations["logout_api_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["me_api_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Change Password
     * @description Cambia la contraseña del usuario logueado.
     */
    post: operations["change_password_api_auth_password_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/conexiones": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List All */
    get: operations["list_all_api_conexiones_get"];
    put?: never;
    /** Create */
    post: operations["create_api_conexiones_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/conexiones/probar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Test */
    post: operations["test_api_conexiones_probar_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/conexiones/{cid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove */
    delete: operations["remove_api_conexiones__cid__delete"];
    options?: never;
    head?: never;
    /** Edit */
    patch: operations["edit_api_conexiones__cid__patch"];
    trace?: never;
  };
  "/api/conexiones/{cid}/boards": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Boards */
    get: operations["boards_api_conexiones__cid__boards_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/conexiones/{cid}/campos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fields */
    get: operations["fields_api_conexiones__cid__campos_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cuentas": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Accounts */
    get: operations["accounts_api_cuentas_get"];
    put?: never;
    /** Add Account */
    post: operations["add_account_api_cuentas_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/proyectos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Projects */
    get: operations["projects_api_proyectos_get"];
    put?: never;
    /** Create */
    post: operations["create_api_proyectos_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/proyectos/{pid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Archive */
    delete: operations["archive_api_proyectos__pid__delete"];
    options?: never;
    head?: never;
    /** Edit */
    patch: operations["edit_api_proyectos__pid__patch"];
    trace?: never;
  };
  "/api/cartera": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Portfolio
     * @description Una card por proyecto visible, ordenadas por riesgo.
     */
    get: operations["portfolio_api_cartera_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/proyectos/{pid}/cumplimiento": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Compliance */
    get: operations["compliance_api_proyectos__pid__cumplimiento_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/proyectos/{pid}/sprints/{sid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Sprint Detail */
    get: operations["sprint_detail_api_proyectos__pid__sprints__sid__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/proyectos/{pid}/recalcular": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh */
    post: operations["refresh_api_proyectos__pid__recalcular_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/proyectos/{pid}/tablero": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Board
     * @description Tablero de Jira del sprint activo (solo lectura).
     */
    get: operations["board_api_proyectos__pid__tablero_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/informes/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Preview */
    post: operations["preview_api_informes_preview_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/informes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List All */
    get: operations["list_all_api_informes_get"];
    put?: never;
    /** Save */
    post: operations["save_api_informes_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/informes/{rid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get */
    get: operations["get_api_informes__rid__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/notificaciones": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Mine
     * @description Avisos del usuario; antes revisa sus proyectos si la última corrida fue hace >15 min.
     */
    get: operations["mine_api_notificaciones_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/notificaciones/leer-todas": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Read All */
    post: operations["read_all_api_notificaciones_leer_todas_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/notificaciones/{nid}/leida": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Read One */
    post: operations["read_one_api_notificaciones__nid__leida_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/asistente/mensaje": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Message
     * @description Un turno del chat: el modelo llama tools de solo lectura con tus permisos.
     */
    post: operations["message_api_asistente_mensaje_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/perfil/tokens-mcp": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Tokens */
    get: operations["list_tokens_api_perfil_tokens_mcp_get"];
    put?: never;
    /**
     * Create Token
     * @description Crea un token. El valor crudo se devuelve una sola vez.
     */
    post: operations["create_token_api_perfil_tokens_mcp_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/perfil/tokens-mcp/{tid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke Token */
    delete: operations["revoke_token_api_perfil_tokens_mcp__tid__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AccountIn */
    AccountIn: {
      /** Name */
      name: string;
    };
    /** AccountOut */
    AccountOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
    };
    /** ActiveOut */
    ActiveOut: {
      /** Name */
      name: string;
      /** Day */
      day: number;
      /** Days */
      days: number;
      /** Planned */
      planned: number;
      /** Burned */
      burned: number;
      /** Pct */
      pct: number | null;
    };
    /** BoardCard */
    BoardCard: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "tablero";
      /** Project */
      project: string;
      /** Sprint */
      sprint: string | null;
      /** Todo */
      todo: number;
      /** Doing */
      doing: number;
      /** Blocked */
      blocked: number;
      /** Done */
      done: number;
      /** Done Pct */
      done_pct: number | null;
      /** Time Pct */
      time_pct: number | null;
    };
    /** BoardOut */
    BoardOut: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Key */
      key: string;
    };
    /**
     * CardOut
     * @description Una card del panel de cartera.
     */
    CardOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Account */
      account: string;
      /** Light */
      light: string;
      last: components["schemas"]["SprintOut"] | null;
      active: components["schemas"]["ActiveOut"] | null;
      /** Trend */
      trend: (number | null)[];
      month: components["schemas"]["MonthOut"] | null;
      /** Error */
      error?: string | null;
    };
    /** ChatIn */
    ChatIn: {
      /** Messages */
      messages: components["schemas"]["MsgIn"][];
    };
    /** ChatOut */
    ChatOut: {
      /** Answer */
      answer: string;
      /** Tools */
      tools: string[];
      /** Cards */
      cards?: (
        | components["schemas"]["SprintCard"]
        | components["schemas"]["RiskCard"]
        | components["schemas"]["TrendCard"]
        | components["schemas"]["BoardCard"]
        | components["schemas"]["IssuesCard"]
      )[];
      /**
       * Trace Id
       * Format: uuid
       */
      trace_id: string;
    };
    /** ComplianceOut */
    ComplianceOut: {
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      /** Sprints */
      sprints: components["schemas"]["SprintOut"][];
      /** Months */
      months: components["schemas"]["MonthOut"][];
    };
    /** ConnIn */
    ConnIn: {
      /** Name */
      name: string;
      /**
       * Site
       * Format: uri
       */
      site: string;
      /** Email */
      email: string;
      /** Token */
      token?: string | null;
      /** Sp Field */
      sp_field?: string | null;
      /**
       * Skip Subtasks
       * @default true
       */
      skip_subtasks: boolean;
    };
    /**
     * ConnOut
     * @description Nunca incluye el token: solo sus últimos 4 caracteres.
     */
    ConnOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Kind */
      kind: string;
      /** Site */
      site: string | null;
      /** Email */
      email: string | null;
      /** Token Last4 */
      token_last4: string | null;
      /** Sp Field */
      sp_field: string | null;
      /** Skip Subtasks */
      skip_subtasks: boolean;
      /** Status */
      status: string;
      /** Last Error */
      last_error: string | null;
      /** Checked At */
      checked_at: string | null;
      /**
       * Projects
       * @default 0
       */
      projects: number;
    };
    /** Counts */
    Counts: {
      /** Total */
      total: number;
      /** Todo */
      todo: number;
      /** Doing */
      doing: number;
      /** Blocked */
      blocked: number;
      /** Done */
      done: number;
    };
    /** DetailOut */
    DetailOut: {
      sprint: components["schemas"]["SprintOut"];
      /** Lines */
      lines: components["schemas"]["LineOut"][];
      /** Site */
      site?: string | null;
    };
    /** FieldOut */
    FieldOut: {
      /** Id */
      id: string;
      /** Name */
      name: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Health */
    Health: {
      /** Status */
      status: string;
      /** Version */
      version: string;
    };
    /** IssueItem */
    IssueItem: {
      /** Key */
      key: string;
      /** Title */
      title: string;
      /** Status */
      status: string;
      /** Assignee */
      assignee: string;
      /** Sp */
      sp: number | null;
    };
    /** IssuesCard */
    IssuesCard: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "issues";
      /** Project */
      project: string;
      /** Sprint */
      sprint: string;
      /** Total */
      total: number;
      /** Items */
      items: components["schemas"]["IssueItem"][];
    };
    /** LineOut */
    LineOut: {
      /** Key */
      key: string;
      /** Title */
      title: string;
      /** Status */
      status: string;
      /** Assignee */
      assignee: string | null;
      /** Sp */
      sp: number | null;
      /** Done */
      done: boolean;
      /** Done At */
      done_at: string | null;
      /** Sprints */
      sprints: string[];
      /** Burned */
      burned: boolean;
      /** Burn Sprint */
      burn_sprint: string | null;
      /** Reason */
      reason: string;
    };
    /** LoginIn */
    LoginIn: {
      /** Email */
      email: string;
      /** Password */
      password: string;
    };
    /** Me */
    Me: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** Name */
      name: string;
      /** Role */
      role: string;
      /** Must Change Pwd */
      must_change_pwd: boolean;
    };
    /** MonthOut */
    MonthOut: {
      /** Month */
      month: string;
      /** Planned */
      planned: number;
      /** Burned */
      burned: number;
      /** Pct */
      pct: number | null;
      /** Light */
      light: string;
      /** Sprints */
      sprints: number;
    };
    /** MsgIn */
    MsgIn: {
      /**
       * Role
       * @enum {string}
       */
      role: "user" | "assistant";
      /** Content */
      content: string;
    };
    /** NotificationOut */
    NotificationOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      /** Kind */
      kind: string;
      /** Title */
      title: string;
      /** Body */
      body: string;
      /** Link */
      link: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Read At */
      read_at: string | null;
    };
    /** NotificationsOut */
    NotificationsOut: {
      /** Items */
      items: components["schemas"]["NotificationOut"][];
      /** Unread */
      unread: number;
    };
    /** PasswordIn */
    PasswordIn: {
      /** Current */
      current: string;
      /** New */
      new: string;
    };
    /** Pending */
    Pending: {
      /** Key */
      key: string;
      /** Title */
      title: string;
      /** Status */
      status: string;
      /** Assignee */
      assignee: string | null;
      /** Sp */
      sp: number | null;
    };
    /** PersonOut */
    PersonOut: {
      /** Name */
      name: string;
      /** Planned */
      planned: number;
      /** Burned */
      burned: number;
      /** Pct */
      pct: number | null;
    };
    /** Point */
    Point: {
      /** Label */
      label: string;
      /** Pct */
      pct: number | null;
      /** Light */
      light: string;
      /** Planned */
      planned?: number | null;
      /** Burned */
      burned?: number | null;
    };
    /** PreviewOut */
    PreviewOut: {
      data: components["schemas"]["ReportData"];
      story: components["schemas"]["StoryIn"] | null;
      /** Model */
      model: string;
      /** Ai Error */
      ai_error?: string | null;
    };
    /** ProjectIn */
    ProjectIn: {
      /** Name */
      name: string;
      /**
       * Account Id
       * Format: uuid
       */
      account_id: string;
      /**
       * Conn Id
       * Format: uuid
       */
      conn_id: string;
      /** Board Id */
      board_id: number;
      /** Board Name */
      board_name: string;
      /** From Sprint */
      from_sprint?: string | null;
      /** Managers */
      managers?: string[];
    };
    /** ProjectOut */
    ProjectOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /**
       * Account Id
       * Format: uuid
       */
      account_id: string;
      /** Account */
      account: string;
      /** Conn Id */
      conn_id: string | null;
      /** Board Id */
      board_id: number | null;
      /** Board Name */
      board_name: string | null;
      /** From Sprint */
      from_sprint: string | null;
      /** Managers */
      managers: string[];
    };
    /**
     * ReportData
     * @description Los números del informe: salen del motor, no de la IA.
     */
    ReportData: {
      /** Project */
      project: string;
      /** Account */
      account: string;
      sprint: components["schemas"]["SprintOut"];
      /** Trend */
      trend: components["schemas"]["TrendPoint"][];
      /** Pending */
      pending: components["schemas"]["Pending"][];
      month: components["schemas"]["MonthOut"] | null;
    };
    /** ReportIn */
    ReportIn: {
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      /** Sprint Id */
      sprint_id: string;
      /**
       * Audience
       * @default equipo
       * @enum {string}
       */
      audience: "equipo" | "cliente" | "gerencia";
    };
    /** ReportOut */
    ReportOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Title */
      title: string;
      /** Audience */
      audience: string;
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Author */
      author: string;
      data: components["schemas"]["ReportData"];
      story: components["schemas"]["StoryIn"] | null;
      /** Model */
      model: string | null;
    };
    /** ReportRow */
    ReportRow: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Title */
      title: string;
      /** Audience */
      audience: string;
      /** Project */
      project: string;
      /** Pct */
      pct: number | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Author */
      author: string;
    };
    /** RiskCard */
    RiskCard: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "riesgo";
      /** Items */
      items: components["schemas"]["RiskItem"][];
      /** No Data */
      no_data: string[];
    };
    /** RiskItem */
    RiskItem: {
      /** Project */
      project: string;
      /** Sprint */
      sprint: string;
      /** Pct */
      pct: number | null;
      /** Light */
      light: string;
    };
    /** SaveIn */
    SaveIn: {
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      /** Sprint Id */
      sprint_id: string;
      /**
       * Audience
       * @default equipo
       * @enum {string}
       */
      audience: "equipo" | "cliente" | "gerencia";
      story?: components["schemas"]["StoryIn"] | null;
    };
    /** SprintBoardOut */
    SprintBoardOut: {
      sprint: components["schemas"]["SprintInfo"] | null;
      counts: components["schemas"]["Counts"];
      /** Done Pct */
      done_pct: number | null;
      /** Cards */
      cards: components["schemas"]["TicketOut"][];
      /** Notice */
      notice?: string | null;
    };
    /** SprintCard */
    SprintCard: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "sprint";
      /** Project */
      project: string;
      /** Sprint */
      sprint: string;
      /** State */
      state: string;
      /** Pct */
      pct: number | null;
      /** Light */
      light: string;
      /** Planned */
      planned: number | null;
      /** Burned */
      burned: number | null;
      /** People */
      people: components["schemas"]["Point"][];
    };
    /** SprintInfo */
    SprintInfo: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** State */
      state: string;
      /**
       * Start
       * Format: date-time
       */
      start: string;
      /**
       * End
       * Format: date-time
       */
      end: string;
      /** Day */
      day: number;
      /** Days */
      days: number;
      /** Time Pct */
      time_pct: number;
    };
    /** SprintOut */
    SprintOut: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /**
       * Start
       * Format: date-time
       */
      start: string;
      /**
       * End
       * Format: date-time
       */
      end: string;
      /** State */
      state: string;
      /** Planned */
      planned: number;
      /** Burned */
      burned: number;
      /** Pct */
      pct: number | null;
      /** Light */
      light: string;
      /** Unestimated */
      unestimated: number;
      /** Provisional */
      provisional: boolean;
      /** Goal */
      goal?: string | null;
      /** People */
      people: components["schemas"]["PersonOut"][];
    };
    /** StoryIn */
    StoryIn: {
      /** Resumen */
      resumen: string;
      /** Puntos */
      puntos?: string[];
    };
    /** TestIn */
    TestIn: {
      /**
       * Site
       * Format: uri
       */
      site: string;
      /** Email */
      email: string;
      /** Token */
      token?: string | null;
      /** Conn Id */
      conn_id?: string | null;
    };
    /** TestOut */
    TestOut: {
      /** Ok */
      ok: boolean;
      /** User */
      user?: string | null;
      /** Sp Field */
      sp_field?: string | null;
      /** Error */
      error?: string | null;
    };
    /** TicketOut */
    TicketOut: {
      /** Key */
      key: string;
      /** Title */
      title: string;
      /** Status */
      status: string;
      /** Lane */
      lane: string;
      /** Type */
      type: string;
      /** Priority */
      priority: string;
      /** Assignee */
      assignee: string | null;
      /** Sp */
      sp: number | null;
      /** Labels */
      labels: string[];
      /** Updated */
      updated: string | null;
    };
    /** TokenIn */
    TokenIn: {
      /** Name */
      name: string;
    };
    /** TokenNew */
    TokenNew: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Last4 */
      last4: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Last Used At */
      last_used_at: string | null;
      /** Token */
      token: string;
    };
    /** TokenOut */
    TokenOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Last4 */
      last4: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Last Used At */
      last_used_at: string | null;
    };
    /** TrendCard */
    TrendCard: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "tendencia";
      /** Project */
      project: string;
      /** Title */
      title: string;
      /** Points */
      points: components["schemas"]["Point"][];
    };
    /** TrendPoint */
    TrendPoint: {
      /** Name */
      name: string;
      /** Planned */
      planned: number;
      /** Burned */
      burned: number;
      /** Pct */
      pct: number | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  login_api_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_api_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me_api_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
    };
  };
  change_password_api_auth_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_all_api_conexiones_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConnOut"][];
        };
      };
    };
  };
  create_api_conexiones_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConnIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConnOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  test_api_conexiones_probar_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TestIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TestOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remove_api_conexiones__cid__delete: {
    parameters: {
      query: {
        confirm: string;
      };
      header?: never;
      path: {
        cid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  edit_api_conexiones__cid__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConnIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConnOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  boards_api_conexiones__cid__boards_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BoardOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  fields_api_conexiones__cid__campos_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FieldOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  accounts_api_cuentas_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountOut"][];
        };
      };
    };
  };
  add_account_api_cuentas_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccountIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  projects_api_proyectos_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectOut"][];
        };
      };
    };
  };
  create_api_proyectos_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  archive_api_proyectos__pid__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  edit_api_proyectos__pid__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  portfolio_api_cartera_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CardOut"][];
        };
      };
    };
  };
  compliance_api_proyectos__pid__cumplimiento_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ComplianceOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  sprint_detail_api_proyectos__pid__sprints__sid__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pid: string;
        sid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DetailOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  refresh_api_proyectos__pid__recalcular_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  board_api_proyectos__pid__tablero_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SprintBoardOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  preview_api_informes_preview_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReportIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PreviewOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_all_api_informes_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReportRow"][];
        };
      };
    };
  };
  save_api_informes_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SaveIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReportOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_api_informes__rid__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        rid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReportOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  mine_api_notificaciones_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NotificationsOut"];
        };
      };
    };
  };
  read_all_api_notificaciones_leer_todas_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  read_one_api_notificaciones__nid__leida_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        nid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  message_api_asistente_mensaje_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_tokens_api_perfil_tokens_mcp_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenOut"][];
        };
      };
    };
  };
  create_token_api_perfil_tokens_mcp_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenNew"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  revoke_token_api_perfil_tokens_mcp__tid__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        tid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
